### ISSUE TITLE
Correct  "support<at>bloggify<dot>org"  to  "support@bloggify.org"

### ISSUE THREAD

**Issue by shalinibhatt** [Bloggify/emoji#7]
Would like to correct the mail id mentioned here!

<img width="1440" alt="Screenshot 1946-08-01 at 5 48 12 PM" src="https://github.com/user-attachments/assets/c6bf7528-a772-4fe3-9f71-b48085893b91">

**Comment by IonicaBizau** [comment]
That is by design. 😁

**Comment by shalinibhatt** [comment]
glad that I asked :p
